[project]
name = "unet"
version = "0.1.0"
description = "PyTorch implementation of the U-Net architecture"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.11.2",
    "pandas>=3.0.6",
    "pytest>=9.1.1",
    "scikit-learn>=1.9.1",
    "torch",
    "torchvision",
]

[tool.uv.sources]
torch = [
  { index = "pytorch-cu132", marker = "sys_platform == 'linux' or sys_platform == 'win32'" },
]
torchvision = [
  { index = "pytorch-cu132", marker = "sys_platform == 'linux' or sys_platform == 'win32'" },
]

[[tool.uv.index]]
name="pytorch-cu132"
url="https://download.pytorch.org/whl/cu132"
explicit=true
